<!DOCTYPE html>
<html lang="en" class="h-100">
  <head >
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>Heat Transfer Printing Services</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/sticky-footer-navbar/">
     <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    
    <!-- Bootstrap core CSS -->
    <link href="assets/dist/css/bootstrap.min.css" rel="stylesheet">
   
    
    <!-- Custom styles for this template -->
    <link href="css/pop-up-login.css" rel="stylesheet">
    <link href="css/sticky-footer-navbar.css" rel="stylesheet">
    <link href="css/services.css" rel="stylesheet">
    
<style>
        .navbar-brand{
        margin-left: -10px
      }
      .navbar-custom { 
        background-color: #EBECF0; 
      } 

      .navbar-nav > li{
        margin-left:2px;
        margin-right:2px;
        font-size: 15px;
      }
  
</style>
  </head>
<?php
    include('includes/clientnav.php'); 
?>
    <body>
        
        <div class="slideshow-container">
            <img src="img/heat-transfer.jpg" style="width: 100%" >
            <div class="content">
                <h1>Heat Transfer Printing</h1>
            </div>
        </div>
        
<div class="description" >   
    <div class="container1">
        <div class="row" style="margin-right:15px;">
        
    
            <div class="col-sm"  >
                <img src="img/heat-transfer-machine1.jpg" class="img-fluid" >
            </div>      
            <div class="col-sm">
                <div class="custom-heat-header" style="width: 600px;padding-top: 20px;">
                            <h2>What is Heat Transfer (Vinyl Printing)?</h2>
                            <h6>The heat transfer process is a two-stage process that involves creating a negative image, that will be pressed onto a garment and the actual heating and pressing of a transfer image onto the garment.  Today’s modern form of heat transfer printing includes methods and techniques from both dye and direct to garment printing.
                                Computers do most of the work during the design process as they are used to calculate the different amounts of ink and colour that will be used to create the images.  Computers will also create a mirrored-negative that will then be pressed onto a target garment.
                                Production defects are minimized with the computer aided process as users are able to view the print as a computer-generated image before the actual printing begins. 
                                Images generated by the computer are printed onto a transfer paper, where the papers only purpose is to “hold” the image until it is placed on the target object (clothing, ceramic mug, etc..).  The positioned image is then heated and pressed onto the target object and allowed to cool.

                            </h6>
                </div>            
        </div>                
    </div>              
              
        
        
            
    <div class="row" style="margin:auto;display: contents;">
                <div class="column" >
                        <div class="heat-printing-example">
                            <h1>Examples Of Heat Transfer Printing</h2>
                            <h5>Heat Transfer printing is a popular choice and works well with t shirts, jerseys and hoodies.</h5>
                            
                            <img src="img/example.jpg" style="padding-right:70px;">
                            <img src="img/example2.jpg" style="padding-right:70px;">
                            <img src="img/example3.jpg" style="padding-right:70px;">
                            <img src="img/example4.jpg"  style="padding-right:70px;">
                        </div>
                </div>
    </div>      
    
            <div class="column" >
                <div class="color" >
                    <h2>Your Colour You Choose</h2>
                    <h5>Colour Available</h5>
                    <img src="img/light blue.png" style="border-radius: 50%;padding-right:10px;">
                        <img src="img/rose pink.jpg" style="border-radius: 50%;padding-right:10px;">
                        <img src="img/maroon.jpg" style="border-radius: 50%;padding-right:10px;">
                        <img src="img/yellow.jpg" style="border-radius: 50%;padding-right:10px;">

                </div>
</div>

                    


                
                 
            
        
   
    </body>
    
     <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="assets/dist/js/bootstrap.bundle.js"></script>

</html>
<?php
include('includes/footer.php');
?>